### ISSUE TITLE
Message not sending ack() or reject()

### ISSUE THREAD

**Issue by famagusta** [depop/celery-message-consumer#19]
I have noticed that on restart celery worker, sometimes the below error comes

Messages for task '**.**.**' are not sending an ack() or a reject(). This needs attention. Assuming some kind of error and requeueing the message.

Is there something I can do to avoid it? It doesn't really hurt anything except retry a message
since message consumer is an idempotent function. But it still turns up in the error logs.

**Comment by anentropic** [comment]
the error comes from this line:
https://github.com/depop/celery-message-consumer/blob/master/event_consumer/handlers.py#L401

we have not seen it in our systems, it may depend how you kill the worker

Celery docs suggest use SIGTERM rather than SIGKILL
https://docs.celeryproject.org/en/latest/userguide/workers.html#stopping-the-worker
(I don't know if this is the cause of that error logging though)

**Comment by famagusta** [comment]
Thanks
